// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdfNNAmoxu2hx42nqtbU7WcgkKY2Rb034',
    appId: '1:59189148175:web:30b3f5b5e2cd80c980c17a',
    messagingSenderId: '59189148175',
    projectId: 'class-1205a',
    authDomain: 'class-1205a.firebaseapp.com',
    storageBucket: 'class-1205a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHRj75tMa4S1SX_OktZQOBPgsTBkVPdio',
    appId: '1:59189148175:android:dbdd264d564fb17280c17a',
    messagingSenderId: '59189148175',
    projectId: 'class-1205a',
    storageBucket: 'class-1205a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfD3BjO53X2YggMJSrd6CXWE4DQrwz96w',
    appId: '1:59189148175:ios:f4cb37237325640b80c17a',
    messagingSenderId: '59189148175',
    projectId: 'class-1205a',
    storageBucket: 'class-1205a.firebasestorage.app',
    iosBundleId: 'com.example.classApp',
  );
}
